version: '3.8'

services:
  python-dev:
    build: .
    container_name: python-dev-container
    volumes:
      - ./Projects:/workspace/projects
      - ~/.ssh:/workspace/ssh:ro
    ports:
      - "8888:8888" # Jupyter Notebook (if needed)
    environment:
      - DEBIAN_FRONTEND=noninteractive
    command: ["/bin/bash", "-c", "/workspace/setup-ssh.sh && tail -f /dev/null"]
    restart: unless-stopped
